
---
- name: Add ec2
  hosts: localhost
  tasks:
  # Basic provisioning example
  - amazon.aws.ec2:
      key_name: laptop
      instance_type: t2.micro
      image: ami-05cd35b907b4ffe77
      wait: yes
      count: 5
      region: us-east-1